CREATE TABLE SMES.CM_DELIVER_ORDER_T
(
  DELIVERY_ID   VARCHAR2(255 BYTE)              NOT NULL,
  INOUT_FLAG    NUMBER(5),
  VTEXT         VARCHAR2(255 BYTE),
  TVKORG        VARCHAR2(255 BYTE),
  VGBEL         VARCHAR2(255 BYTE),
  VBELN         VARCHAR2(255 BYTE),
  NAME1         VARCHAR2(255 BYTE),
  NAME2         VARCHAR2(255 BYTE),
  NAME3         VARCHAR2(255 BYTE),
  NAME_TYPE     VARCHAR2(255 BYTE),
  WASTE_VAL     NUMBER,
  AESKD         VARCHAR2(255 BYTE),
  ABLAD         VARCHAR2(255 BYTE),
  VTEXT1        VARCHAR2(255 BYTE),
  ARKTX         VARCHAR2(255 BYTE),
  MATNR         VARCHAR2(255 BYTE),
  DW            VARCHAR2(255 BYTE),
  KWMENG        NUMBER,
  LFIMG         NUMBER,
  WADAT         DATE,
  WADAT_IST     DATE,
  VSBED         VARCHAR2(255 BYTE),
  AENAM         VARCHAR2(255 BYTE),
  WBSTA         VARCHAR2(255 BYTE),
  FKSTA         VARCHAR2(255 BYTE),
  IS_ERP_ORDER  VARCHAR2(255 BYTE),
  ANZPK         VARCHAR2(255 BYTE),
  BEZEI         VARCHAR2(255 BYTE),
  BLDAT         VARCHAR2(255 BYTE),
  BOLNR         VARCHAR2(255 BYTE),
  BSTKD         VARCHAR2(255 BYTE),
  BWTAR         VARCHAR2(255 BYTE),
  FZ            VARCHAR2(255 BYTE),
  FZMC          VARCHAR2(255 BYTE),
  JHDBZ         VARCHAR2(255 BYTE),
  KONDM         VARCHAR2(255 BYTE),
  KUNNR         VARCHAR2(255 BYTE),
  LGORT         VARCHAR2(255 BYTE),
  POSNR         VARCHAR2(255 BYTE),
  ROUTE         VARCHAR2(255 BYTE),
  SHRDW         VARCHAR2(255 BYTE),
  SHRDWMC       VARCHAR2(255 BYTE),
  TRAID         VARCHAR2(255 BYTE),
  TRATY         VARCHAR2(255 BYTE),
  VGPOS         VARCHAR2(255 BYTE),
  VKORG         VARCHAR2(255 BYTE),
  VSTEL         VARCHAR2(255 BYTE),
  VRKME         VARCHAR2(255 BYTE),
  MSEHL         VARCHAR2(255 BYTE),
  ZDDSY         NUMBER,
  RFMNG         NUMBER,
  ZSDF          VARCHAR2(255 BYTE)
)

CREATE TABLE SMES.CM_ERPSDDATA_SHIPMENTPOINT_T
(
  YUNSFSBM  VARCHAR2(20 BYTE),
  WULBM     VARCHAR2(20 BYTE),
  JINCCDBM  VARCHAR2(20 BYTE)
)

CREATE TABLE SMES.CM_ERP_LOCATION_T
(
  LOCATION_ID       VARCHAR2(255 BYTE)          NOT NULL,
  LOCATION_NAME     VARCHAR2(255 BYTE),
  LOCATION_DISNAME  VARCHAR2(255 BYTE)
)

CREATE TABLE SMES.CM_ERP_ROUTE_T
(
  ROUTE_ID       VARCHAR2(255 BYTE)             NOT NULL,
  ROUTE_NAME     VARCHAR2(255 BYTE),
  ROUTE_DISNAME  VARCHAR2(255 BYTE)
)

CREATE TABLE SMES.CM_ERP_TRAFFICTYPE_T
(
  TRAFFICTYPE_ID       VARCHAR2(255 BYTE)       NOT NULL,
  TRAFFICTYPE_NAME     VARCHAR2(255 BYTE),
  TRAFFICTYPE_DISNAME  VARCHAR2(255 BYTE)
)

CREATE TABLE SMES.CM_IO_SITE_T
(
  IO_SITE_CODE  VARCHAR2(255 BYTE)              NOT NULL,
  IO_SITE_NAME  VARCHAR2(255 BYTE)              NOT NULL
)

CREATE TABLE SMES.CM_MEAS_DTL_CANCEL_T
(
  REC_ID          VARCHAR2(255 BYTE),
  MEAS_ORDER_ID   VARCHAR2(255 BYTE),
  MEAS_TYPE_ID    VARCHAR2(255 BYTE),
  MEAS_SHEET_ID   VARCHAR2(255 BYTE),
  MEAS_TICKET_ID  VARCHAR2(255 BYTE),
  GAUGE_ID        VARCHAR2(255 BYTE),
  GAUGE_NAME      VARCHAR2(255 BYTE),
  MTRL_CODE       VARCHAR2(255 BYTE),
  MTRL_NAME       VARCHAR2(255 BYTE),
  TRUCK_NO        VARCHAR2(255 BYTE),
  IS_MAIN         NUMBER(5),
  VAL             NUMBER,
  DES             VARCHAR2(255 BYTE),
  GAUGER          VARCHAR2(255 BYTE),
  SAVE_TIME       VARCHAR2(255 BYTE),
  DATE1           VARCHAR2(255 BYTE),
  DATE2           VARCHAR2(255 BYTE),
  DATE3           VARCHAR2(255 BYTE),
  DATE4           VARCHAR2(255 BYTE),
  DATE5           VARCHAR2(255 BYTE),
  VAL1            NUMBER,
  VAL2            NUMBER,
  VAL3            NUMBER,
  VAL4            NUMBER,
  VAL5            NUMBER,
  VAL6            NUMBER,
  VAL7            NUMBER,
  VAL8            NUMBER,
  VAL9            NUMBER,
  VAL10           NUMBER,
  VAL11           NUMBER,
  VAL12           NUMBER,
  VAL13           NUMBER,
  VAL14           NUMBER,
  VAL15           NUMBER,
  TEXT1           VARCHAR2(255 BYTE),
  TEXT2           VARCHAR2(255 BYTE),
  TEXT3           VARCHAR2(255 BYTE),
  TEXT4           VARCHAR2(255 BYTE),
  TEXT5           VARCHAR2(255 BYTE),
  TEXT6           VARCHAR2(255 BYTE),
  ID              NUMBER(11)                    NOT NULL
)

CREATE TABLE SMES.CM_MEAS_DTL_TRG
(
  REC_ID          VARCHAR2(255 BYTE),
  MEAS_ORDER_ID   VARCHAR2(255 BYTE),
  MEAS_TYPE_ID    VARCHAR2(255 BYTE),
  MEAS_SHEET_ID   VARCHAR2(255 BYTE),
  MEAS_TICKET_ID  VARCHAR2(255 BYTE),
  GAUGE_ID        VARCHAR2(255 BYTE),
  GAUGE_NAME      VARCHAR2(255 BYTE),
  MTRL_CODE       VARCHAR2(255 BYTE),
  MTRL_NAME       VARCHAR2(255 BYTE),
  TRUCK_NO        VARCHAR2(255 BYTE),
  IS_MAIN         NUMBER(5),
  VAL             NUMBER,
  DES             VARCHAR2(255 BYTE),
  GAUGER          VARCHAR2(255 BYTE),
  SAVE_TIME       VARCHAR2(255 BYTE),
  DATE1           VARCHAR2(255 BYTE),
  DATE2           VARCHAR2(255 BYTE),
  DATE3           VARCHAR2(255 BYTE),
  DATE4           VARCHAR2(255 BYTE),
  DATE5           VARCHAR2(255 BYTE),
  VAL1            NUMBER,
  VAL2            NUMBER,
  VAL3            NUMBER,
  VAL4            NUMBER,
  VAL5            NUMBER,
  VAL6            NUMBER,
  VAL7            NUMBER,
  VAL8            NUMBER,
  VAL9            NUMBER,
  VAL10           NUMBER,
  VAL11           NUMBER,
  VAL12           NUMBER,
  VAL13           NUMBER,
  VAL14           NUMBER,
  VAL15           NUMBER,
  TEXT1           VARCHAR2(255 BYTE),
  TEXT2           VARCHAR2(255 BYTE),
  TEXT3           VARCHAR2(255 BYTE),
  TEXT4           VARCHAR2(255 BYTE),
  TEXT5           VARCHAR2(255 BYTE),
  TEXT6           VARCHAR2(255 BYTE),
  TEXT7           VARCHAR2(255 BYTE),
  TEXT8           VARCHAR2(255 BYTE),
  TEXT9           VARCHAR2(255 BYTE),
  TEXT10          VARCHAR2(255 BYTE),
  TEXT11          VARCHAR2(255 BYTE),
  TEXT12          VARCHAR2(255 BYTE),
  TEXT13          VARCHAR2(255 BYTE),
  TEXT14          VARCHAR2(255 BYTE),
  OPT_TIME        DATE,
  OPT_MONTH       VARCHAR2(2 BYTE),
  OPT_USER        VARCHAR2(255 BYTE),
  OPT_DES         VARCHAR2(2000 BYTE)
)

CREATE TABLE SMES.CM_MEAS_FORMULA_T
(
  MEAS_TYPE_ID  VARCHAR2(255 BYTE)              NOT NULL,
  CALC_ORDER    NUMBER(11)                      NOT NULL,
  FIELD_NAME    VARCHAR2(255 BYTE)              NOT NULL,
  FORMULA       VARCHAR2(255 BYTE)
)

CREATE TABLE SMES.CM_MEAS_REC_TB
(
  MEAS_REC_ID       NUMBER                      NOT NULL,
  SMTINOUT_BILL_ID  NUMBER                      NOT NULL,
  BEG_SHIFT_TIME    DATE,
  END_SHIFT_TIME    DATE,
  INSTR_ID          NUMBER,
  MEAS_USER_ID      VARCHAR2(200 BYTE),
  CRT_USER_ID       VARCHAR2(200 BYTE),
  ADIT_USER_ID      VARCHAR2(200 BYTE),
  MEAS_TYPE_ID      NUMBER,
  MEAR_VAL          NUMBER                      NOT NULL,
  MEAS_TIME         DATE                        NOT NULL,
  CON_VAL           NUMBER,
  CRT_TIME          DATE,
  STATE             NUMBER,
  MEMO              VARCHAR2(200 BYTE),
  MAIN_MEAS_REC_ID  NUMBER,
  SUB_MEAS_TYPE     NUMBER,
  BALANCE_DATA_ID   NUMBER,
  TRUCK_NO          VARCHAR2(128 BYTE)
)

CREATE TABLE SMES.CM_MEAS_SCALE_T
(
  REC_ID          VARCHAR2(200 BYTE),
  MEAS_ORDER_ID   VARCHAR2(200 BYTE),
  MEAS_TYPE_ID    VARCHAR2(200 BYTE),
  MEAS_SHEET_ID   VARCHAR2(200 BYTE),
  MEAS_TICKET_ID  VARCHAR2(200 BYTE),
  GAUGE_ID        VARCHAR2(200 BYTE),
  GAUGE_NAME      VARCHAR2(255 BYTE),
  MTRL_CODE       VARCHAR2(200 BYTE),
  MTRL_NAME       VARCHAR2(255 BYTE),
  TRUCK_NO        VARCHAR2(1024 BYTE),
  IS_MAIN         NUMBER,
  VAL             NUMBER,
  DES             VARCHAR2(2000 BYTE),
  GAUGER          VARCHAR2(32 BYTE),
  SAVE_TIME       VARCHAR2(200 BYTE),
  DATE1           VARCHAR2(200 BYTE),
  DATE2           VARCHAR2(200 BYTE),
  DATE3           VARCHAR2(200 BYTE),
  DATE4           VARCHAR2(200 BYTE),
  DATE5           VARCHAR2(200 BYTE),
  VAL1            NUMBER,
  VAL2            NUMBER,
  VAL3            NUMBER,
  VAL4            NUMBER,
  VAL5            NUMBER,
  VAL6            NUMBER,
  VAL7            NUMBER,
  VAL8            NUMBER,
  VAL9            NUMBER,
  VAL10           NUMBER,
  VAL11           NUMBER,
  VAL12           NUMBER,
  VAL13           NUMBER,
  VAL14           NUMBER,
  VAL15           NUMBER,
  TEXT1           VARCHAR2(255 BYTE),
  TEXT2           VARCHAR2(255 BYTE),
  TEXT3           VARCHAR2(255 BYTE),
  TEXT4           VARCHAR2(255 BYTE),
  TEXT5           VARCHAR2(255 BYTE),
  TEXT6           VARCHAR2(255 BYTE),
  TEXT7           VARCHAR2(255 BYTE),
  TEXT8           VARCHAR2(255 BYTE),
  TEXT9           VARCHAR2(255 BYTE),
  TEXT10          VARCHAR2(255 BYTE),
  TEXT11          VARCHAR2(255 BYTE),
  TEXT12          VARCHAR2(255 BYTE),
  TEXT13          VARCHAR2(255 BYTE),
  TEXT14          VARCHAR2(255 BYTE)
)

CREATE TABLE SMES.CM_MEAS_SCALE_T_TRG
(
  REC_ID          VARCHAR2(200 BYTE),
  MEAS_ORDER_ID   VARCHAR2(200 BYTE),
  MEAS_TYPE_ID    VARCHAR2(200 BYTE),
  MEAS_SHEET_ID   VARCHAR2(200 BYTE),
  MEAS_TICKET_ID  VARCHAR2(200 BYTE),
  GAUGE_ID        VARCHAR2(200 BYTE),
  GAUGE_NAME      VARCHAR2(255 BYTE),
  MTRL_CODE       VARCHAR2(200 BYTE),
  MTRL_NAME       VARCHAR2(255 BYTE),
  TRUCK_NO        VARCHAR2(1024 BYTE),
  IS_MAIN         NUMBER,
  VAL             NUMBER,
  DES             VARCHAR2(2000 BYTE),
  GAUGER          VARCHAR2(32 BYTE),
  SAVE_TIME       VARCHAR2(200 BYTE),
  DATE1           VARCHAR2(200 BYTE),
  DATE2           VARCHAR2(200 BYTE),
  DATE3           VARCHAR2(200 BYTE),
  DATE4           VARCHAR2(200 BYTE),
  DATE5           VARCHAR2(200 BYTE),
  VAL1            NUMBER,
  VAL2            NUMBER,
  VAL3            NUMBER,
  VAL4            NUMBER,
  VAL5            NUMBER,
  VAL6            NUMBER,
  VAL7            NUMBER,
  VAL8            NUMBER,
  VAL9            NUMBER,
  VAL10           NUMBER,
  VAL11           NUMBER,
  VAL12           NUMBER,
  VAL13           NUMBER,
  VAL14           NUMBER,
  VAL15           NUMBER,
  TEXT1           VARCHAR2(255 BYTE),
  TEXT2           VARCHAR2(255 BYTE),
  TEXT3           VARCHAR2(255 BYTE),
  TEXT4           VARCHAR2(255 BYTE),
  TEXT5           VARCHAR2(255 BYTE),
  TEXT6           VARCHAR2(255 BYTE),
  TEXT7           VARCHAR2(255 BYTE),
  TEXT8           VARCHAR2(255 BYTE),
  TEXT9           VARCHAR2(255 BYTE),
  TEXT10          VARCHAR2(255 BYTE),
  TEXT11          VARCHAR2(255 BYTE),
  TEXT12          VARCHAR2(255 BYTE),
  TEXT13          VARCHAR2(255 BYTE),
  TEXT14          VARCHAR2(255 BYTE),
  OPT_USER        VARCHAR2(200 BYTE),
  OPT_TIME        DATE,
  OPT_IP          VARCHAR2(200 BYTE),
  OPT_TYPE        VARCHAR2(200 BYTE)
)

CREATE TABLE SMES.CM_MEAS_SHEET_T
(
  SERIAL_NUMBER  VARCHAR2(255 BYTE)             NOT NULL,
  GROSS_WEIGHT   NUMBER,
  NET_WEIGHT     NUMBER,
  MEAS_TIME      DATE,
  GAUGER         VARCHAR2(255 BYTE),
  SAVE_TIME      DATE,
  OIL_NAME       VARCHAR2(255 BYTE),
  DELIVERY_DATE  DATE,
  ORGN_STATION   VARCHAR2(255 BYTE),
  DEST_STATION   VARCHAR2(255 BYTE),
  TANK_NO        VARCHAR2(255 BYTE)
)

CREATE TABLE SMES.CM_MEAS_STRUCT_T
(
  MEAS_TYPE_ID  VARCHAR2(32 BYTE)               NOT NULL,
  FIELD_NAME    VARCHAR2(255 BYTE)              NOT NULL,
  CN_NAME       VARCHAR2(255 BYTE),
  ALIGN         VARCHAR2(255 BYTE),
  WIDTH         NUMBER(5),
  DISP_ORDER    NUMBER(5),
  ISHAND        NUMBER(11),
  UICTRLNAME    VARCHAR2(255 BYTE)
)

CREATE TABLE SMES.CM_MEAS_TICKET_PRNT_T
(
  MEAS_TICKET_ID  VARCHAR2(255 BYTE),
  TICKET_NO       VARCHAR2(255 BYTE)            NOT NULL,
  PRINT_TIME      DATE
)

CREATE TABLE SMES.CM_MEAS_TICKET_T
(
  MEAS_TICKET_ID   VARCHAR2(255 BYTE)           NOT NULL,
  TICKET_NO        VARCHAR2(255 BYTE),
  BARGE_NO         VARCHAR2(255 BYTE),
  PRINT_NUMBER     NUMBER(11),
  PRINT_TIME       DATE,
  MEAS_TICKET_VAL  NUMBER,
  WATER_WEIGHT     NUMBER,
  NET_WEIGHT       NUMBER,
  DES              VARCHAR2(255 BYTE),
  GAUGER           VARCHAR2(255 BYTE),
  AUDITOR          VARCHAR2(255 BYTE),
  SAVE_TIME        DATE,
  SEQNO            NUMBER(11),
  AMOUNT           NUMBER(11),
  SPEC             VARCHAR2(255 BYTE),
  WATER_RATIO      NUMBER(11),
  DATA1            NUMBER(11),
  DATA2            NUMBER(11),
  DATA3            NUMBER(11),
  TEXT1            VARCHAR2(255 BYTE),
  TEXT2            VARCHAR2(255 BYTE),
  TEXT3            VARCHAR2(255 BYTE),
  GAUGER_ID        VARCHAR2(255 BYTE),
  MTRL_CODE        VARCHAR2(255 BYTE),
  MTRL_NAME        VARCHAR2(255 BYTE)
)

CREATE TABLE SMES.CM_MEAS_TYPE_T
(
  MEAS_TYPE_ID    VARCHAR2(255 BYTE),
  MEAS_TYPE_NAME  VARCHAR2(255 BYTE)
)

CREATE TABLE SMES.CM_MODI_LOG_T
(
  REC_ID      VARCHAR2(255 BYTE)                NOT NULL,
  TABLE_NAME  VARCHAR2(255 BYTE)                NOT NULL,
  FIELD_NAME  VARCHAR2(255 BYTE)                NOT NULL,
  ORIG_VAL    VARCHAR2(255 BYTE),
  NEW_VAL     VARCHAR2(255 BYTE),
  USERID      VARCHAR2(255 BYTE),
  MODI_DATE   DATE                              NOT NULL
)

CREATE TABLE SMES.CM_MTRL_TRAIN_MES_T
(
  TRAIN_MTRL_NAME  VARCHAR2(400 BYTE),
  MES_MTRL_NAME    VARCHAR2(400 BYTE),
  MTRL_CODE        VARCHAR2(20 BYTE)
)

CREATE TABLE SMES.CM_ORDER_TICKET_T
(
  ORDERID   VARCHAR2(255 BYTE)                  NOT NULL,
  TICKETID  VARCHAR2(255 BYTE),
  ORDERVAL  VARCHAR2(255 BYTE),
  ID        INTEGER
)

CREATE TABLE SMES.CM_PICKLIST_DTLREC_T
(
  PICKLIST_ID   NUMBER,
  REC_TYPE      NUMBER,
  MOVE_ID       NUMBER,
  NODE_ID       NUMBER,
  MTRL_ID       NUMBER,
  NODE_TYPE_ID  NUMBER,
  SHIPMENT_ID   NUMBER,
  DLV_RCV_FLG   NUMBER,
  BEG_RD_TIME   DATE,
  END_RD_TIME   DATE,
  DIFF_VAL      NUMBER,
  PRE_VAL       NUMBER,
  PRE_TIME      DATE,
  AFT_VAL       NUMBER,
  AFT_TIME      DATE,
  REMARK        VARCHAR2(200 BYTE)
)

CREATE TABLE SMES.CM_PICKLIST_NODE_T
(
  MOVE_ID       NUMBER,
  SHIPMENT_ID   NUMBER,
  NODE_ID       NUMBER,
  NODE_TYPE_ID  NUMBER,
  BEG_RD_TIME   DATE,
  END_RD_TIME   DATE,
  DLV_RCV_FLG   NUMBER
)

CREATE TABLE SMES.CM_PICKLIST_QUERY_T
(
  PICKLIST_ID  NUMBER,
  MTRL_ID      NUMBER,
  ID           NUMBER,
  REC_TYPE     NUMBER,
  INOUT_FLAG   NUMBER,
  SR_NODE      NUMBER,
  SR_NAME      VARCHAR2(400 BYTE),
  SR_TYPE      NUMBER,
  TG_NODE      NUMBER,
  TG_NAME      VARCHAR2(400 BYTE),
  TG_TYPE      NUMBER,
  BEG_TIME     DATE,
  END_TIME     DATE,
  PRE_VAL      NUMBER,
  PRE_TIME     DATE,
  AFT_VAL      NUMBER,
  AFT_TIME     DATE,
  MES_FCTR_ID  NUMBER
)

CREATE TABLE SMES.CM_PICKLIST_T
(
  PICKLIST_ID       NUMBER                      NOT NULL,
  PICKLIST_USER_ID  VARCHAR2(40 BYTE)           NOT NULL,
  PICKLIST_TM       DATE                        NOT NULL,
  PICKLIST_DATE     DATE
)

CREATE TABLE SMES.CM_PRINT_TEMPLATE_APP_T
(
  PRINT_TEMPLATE_NAME  VARCHAR2(255 BYTE)       NOT NULL,
  MEAS_TYPE_ID         VARCHAR2(255 BYTE)       NOT NULL,
  IO_SITE_CODE         VARCHAR2(255 BYTE)       NOT NULL
)

CREATE TABLE SMES.CM_PRNT_TMPLT_DTL_T
(
  PRINT_TEMPLATE_NAME  VARCHAR2(255 BYTE)       NOT NULL,
  PROPERTY_NAME        VARCHAR2(32 BYTE)        NOT NULL,
  CN_NAME              VARCHAR2(255 BYTE),
  STR_FONT             VARCHAR2(255 BYTE),
  STR_SIZE             VARCHAR2(255 BYTE),
  STR_LOCATION         VARCHAR2(255 BYTE),
  TEXT_ALIGN           VARCHAR2(255 BYTE),
  UP_PROPERTY_NAME     VARCHAR2(32 BYTE)
)

CREATE TABLE SMES.CM_SHIPMENT_MOVE_REC_T
(
  MOVE_ID      NUMBER                           NOT NULL,
  SR_AREA      NUMBER,
  SR_NODE      NUMBER                           NOT NULL,
  SR_NAME      VARCHAR2(400 BYTE),
  SR_TYPE      NUMBER,
  SR_MTRL      NUMBER,
  TG_AREA      NUMBER,
  TG_NODE      NUMBER                           NOT NULL,
  TG_NAME      VARCHAR2(400 BYTE),
  TG_TYPE      NUMBER,
  TG_MTRL      NUMBER,
  BEG_RD_TIME  DATE,
  END_RD_TIME  DATE,
  MES_FCTR_ID  NUMBER
)

CREATE TABLE SMES.CM_SHIPMENT_MTRL_MOVE_REC_T
(
  MOVE_ID      NUMBER,
  SR_AREA      NUMBER,
  SR_NODE      NUMBER,
  SR_MTRL      NUMBER,
  TG_AREA      NUMBER,
  TG_NODE      NUMBER,
  TG_MTRL      NUMBER,
  BEG_RD_TIME  DATE,
  END_RD_TIME  DATE,
  MES_FCTR_ID  NUMBER
)

CREATE TABLE SMES.CM_TRAC_MEAS_REC_T
(
  MEAS_REC_ID    NUMBER                         NOT NULL,
  PRE_READ_TIME  DATE,
  AFT_READ_TIME  DATE,
  TEMP           NUMBER,
  DNSTY          NUMBER,
  VCF_VAL        NUMBER,
  TEMP_ADJ_VAL   NUMBER,
  CUBAGE         NUMBER,
  VP_VAL         NUMBER,
  WEIGHT         NUMBER,
  VHCL_NO        VARCHAR2(200 BYTE),
  GROSS_WEIGHT   NUMBER,
  VHCL_WEIGHT    NUMBER,
  NET_WEIGHT     NUMBER,
  WATER_PERCENT  NUMBER,
  SPEED          NUMBER,
  ADJ_COEF       NUMBER,
  IS_MAIN_MEAS   NUMBER,
  SELF_WEIGHT    NUMBER,
  MEMO           VARCHAR2(4000 BYTE),
  WTR_WEIGHT     NUMBER,
  WEIGHT_CODE    VARCHAR2(200 BYTE)
)

CREATE TABLE SMES.CM_TRAIN_MEAS_REC_T
(
  SHUNXH   NUMBER,
  CHEH     VARCHAR2(16 BYTE),
  CHEX     VARCHAR2(32 BYTE),
  BIAOH    VARCHAR2(32 BYTE),
  YOUG     NUMBER,
  SHUIF    NUMBER,
  SHICTJ   NUMBER,
  JILWD    NUMBER,
  SHIYWD   NUMBER,
  SHIMD    NUMBER,
  XIS1     NUMBER,
  FACZL    NUMBER,
  XIS2     NUMBER,
  CHANPMC  VARCHAR2(128 BYTE),
  LIUK     VARCHAR2(128 BYTE),
  XIS3     NUMBER,
  DAOZ     VARCHAR2(128 BYTE),
  YUNDH    VARCHAR2(32 BYTE),
  QIANFH   VARCHAR2(64 BYTE),
  JILRQ    DATE,
  JILRY    VARCHAR2(64 BYTE),
  STATE    NUMBER                               DEFAULT 0
)

CREATE TABLE SMES.CM_TRAIN_MEAS_REC_TEMP_T
(
  SHUNXH   NUMBER,
  CHEH     VARCHAR2(16 BYTE),
  CHEX     VARCHAR2(32 BYTE),
  BIAOH    VARCHAR2(32 BYTE),
  YOUG     NUMBER,
  SHUIF    NUMBER,
  SHICTJ   NUMBER,
  JILWD    NUMBER,
  SHIYWD   NUMBER,
  SHIMD    NUMBER,
  XIS1     NUMBER,
  FACZL    NUMBER,
  XIS2     NUMBER,
  CHANPMC  VARCHAR2(128 BYTE),
  LIUK     VARCHAR2(128 BYTE),
  XIS3     NUMBER,
  DAOZ     VARCHAR2(128 BYTE),
  YUNDH    VARCHAR2(32 BYTE),
  QIANFH   VARCHAR2(64 BYTE),
  JILRQ    DATE,
  JILRY    VARCHAR2(64 BYTE)
)

CREATE TABLE SMES.CM_TRANS_MEAS_MAP_T
(
  TRANS_MEAS_MAP_ID  NUMBER                     NOT NULL,
  TRAN_TYPE_ID       NUMBER,
  MEAS_TYPE_ID       NUMBER
)

CREATE TABLE SMES.CM_TRUCK_MEAS_REC_T
(
  MEAS_REC_ID    NUMBER                         NOT NULL,
  PRE_READ       DATE,
  AFT_READ       DATE,
  WEIGHT         NUMBER,
  VHCL_NO        VARCHAR2(200 BYTE),
  GROSS_WEIGHT   NUMBER,
  VHCL_WEIGHT    NUMBER,
  NET_WEIGHT     NUMBER,
  WATER_PERCENT  NUMBER,
  WTR_WEIGHT     NUMBER,
  SELF_WEIGHT    NUMBER,
  MEMO           VARCHAR2(4000 BYTE),
  IS_MAIN_MEAS   NUMBER
)

CREATE TABLE SMES.CM_WAGON_MEAS_REC_T
(
  MEAS_REC_ID    NUMBER                         NOT NULL,
  WAGON_NO       VARCHAR2(22 BYTE)              NOT NULL,
  PRE_READ       NUMBER                         NOT NULL,
  AFT_READ       NUMBER,
  PRE_READ_TIME  DATE,
  AFT_READ_TIME  DATE,
  TEMP           NUMBER,
  DNSTY          NUMBER,
  VCF_VAL        NUMBER,
  TEMP_ADJ_VAL   NUMBER,
  CUBAGE         NUMBER,
  VP_VAL         NUMBER,
  WEIGHT         NUMBER,
  NET_WEIGHT     NUMBER,
  WATER_PERCENT  NUMBER,
  WATER_HEIGH    NUMBER,
  WTR_WEIGHT     NUMBER,
  MEMO           VARCHAR2(4000 BYTE),
  IS_MAIN_MEAS   NUMBER
)

CREATE TABLE SMES.COM_CONSTRAINTS
(
  TABLE_NAME       VARCHAR2(30 BYTE),
  VERSION_NUM      VARCHAR2(20 BYTE),
  CONSTRAINT_NAME  VARCHAR2(30 BYTE),
  CONSTRAINT_TYPE  VARCHAR2(1 BYTE)
)

CREATE TABLE SMES.COM_CONS_DEF
(
  CONSTRAINT_NAME  VARCHAR2(30 BYTE),
  TABLE_NAME       VARCHAR2(30 BYTE),
  POSITION         NUMBER,
  COLUMN_NAME      VARCHAR2(100 BYTE)
)

CREATE TABLE SMES.COM_INDEXES
(
  TABLE_NAME   VARCHAR2(30 BYTE),
  VERSION_NUM  VARCHAR2(20 BYTE),
  INDEX_NAME   VARCHAR2(27 BYTE),
  UNIQUENESS   VARCHAR2(9 BYTE)
)

CREATE TABLE SMES.COM_IND_DEF
(
  INDEX_NAME       VARCHAR2(30 BYTE),
  TABLE_NAME       VARCHAR2(30 BYTE),
  COLUMN_NAME      VARCHAR2(100 BYTE),
  COLUMN_POSITION  NUMBER
)

CREATE TABLE SMES.COM_SOURCE
(
  NAME         VARCHAR2(30 BYTE),
  VERSION_NUM  VARCHAR2(20 BYTE),
  TYPE         VARCHAR2(12 BYTE),
  LINE         NUMBER,
  TEXT         VARCHAR2(4000 BYTE)
)

CREATE TABLE SMES.COM_TABLES
(
  TABLE_NAME   VARCHAR2(30 BYTE),
  VERSION_NUM  VARCHAR2(20 BYTE)
)

CREATE TABLE SMES.COM_TAB_DEF
(
  TABLE_NAME      VARCHAR2(30 BYTE),
  COLUMN_NAME     VARCHAR2(30 BYTE),
  DATA_TYPE       VARCHAR2(9 BYTE),
  DATA_LENGTH     NUMBER,
  DATA_PRECISION  NUMBER,
  DATA_SCALE      NUMBER,
  NULLABLE        VARCHAR2(1 BYTE),
  COLUMN_ID       NUMBER,
  DEFAULT_LENGTH  NUMBER
)

CREATE TABLE SMES.COM_TRIGGERS
(
  TRIGGER_NAME       VARCHAR2(30 BYTE),
  VERSION_NUM        VARCHAR2(20 BYTE),
  TRIGGER_TYPE       VARCHAR2(16 BYTE),
  TRIGGERING_EVENT   VARCHAR2(227 BYTE),
  TABLE_NAME         VARCHAR2(30 BYTE),
  REFERENCING_NAMES  VARCHAR2(128 BYTE),
  WHEN_CLAUSE        VARCHAR2(100 BYTE),
  STATUS             VARCHAR2(8 BYTE),
  DESCRIPTION        VARCHAR2(4000 BYTE)
)

CREATE TABLE SMES.COM_VIEWS
(
  VIEW_NAME    VARCHAR2(30 BYTE),
  VERSION_NUM  VARCHAR2(20 BYTE)
)

CREATE TABLE SMES.CU_INSTR_MEAS_DTL_TMP
(
  INSTR_DATA_ID   NUMBER                        NOT NULL,
  NODE_ID         NUMBER                        NOT NULL,
  MTRL_ID         NUMBER                        NOT NULL,
  QUTY_RANK_ID    NUMBER                        NOT NULL,
  END_SHIFT_TIME  DATE                          NOT NULL,
  BEG_SHIFT_TIME  DATE                          NOT NULL,
  PRE_VAD_VAL     NUMBER(13,3)
)

CREATE TABLE SMES.CU_RAW_MTRL_T
(
  REC_ID          NUMBER                        NOT NULL,
  SHIFT_END_TIME  DATE                          NOT NULL,
  SDLN_ID         NUMBER                        NOT NULL,
  MTRL_ID         NUMBER                        NOT NULL,
  SDLN_IO_FLAG    NUMBER                        DEFAULT 0                     NOT NULL,
  AREA_VAL        NUMBER                        DEFAULT 0                     NOT NULL,
  SDLN_VAL        NUMBER                        DEFAULT 0                     NOT NULL,
  PRD_SDLN_ID     NUMBER                        NOT NULL,
  PRD_MTRL_ID     NUMBER                        NOT NULL,
  PRD_VAL         NUMBER                        DEFAULT 0                     NOT NULL,
  PRD_RAW_VAL     NUMBER                        DEFAULT 0                     NOT NULL,
  MAKE_VAL        NUMBER                        DEFAULT 0                     NOT NULL,
  MAKE_RAW_VAL    NUMBER                        DEFAULT 0                     NOT NULL,
  WASTAGE         NUMBER                        DEFAULT 0                     NOT NULL,
  COEFFICIENT     NUMBER                        DEFAULT 1                     NOT NULL
)

CREATE TABLE SMES.CU_SLINE_MEAS_T
(
  REC_ID          NUMBER                        NOT NULL,
  SHIFT_END_TIME  DATE                          NOT NULL,
  SLINE_ID        NUMBER                        NOT NULL,
  MTRL_ID         NUMBER                        NOT NULL,
  RANK_ID         NUMBER                        NOT NULL,
  SEGMENT_ID      NUMBER                        NOT NULL,
  REF_VAL         NUMBER,
  AFF_VAL         NUMBER                        NOT NULL,
  SBMT_USER       VARCHAR2(64 BYTE)             NOT NULL,
  SBMT_TM         DATE                          NOT NULL
)

CREATE TABLE SMES.CU_SLINE_REF_T
(
  REC_ID      NUMBER                            NOT NULL,
  QUOTER_ID   NUMBER,
  SLINE_ID    NUMBER                            NOT NULL,
  MTRL_ID     NUMBER,
  RANK_ID     NUMBER,
  SEGMENT_ID  NUMBER                            NOT NULL,
  FACTOR      NUMBER                            DEFAULT 1                     NOT NULL,
  SBMT_USER   VARCHAR2(64 BYTE)                 NOT NULL,
  SBMT_TM     DATE                              NOT NULL
)

CREATE TABLE SMES.CU_STK_MEAS_DTL_CW_T
(
  REC_ID         INTEGER                        NOT NULL,
  MODL_REC_ID    INTEGER,
  INST_VAL       NUMBER,
  CON_ADJ_VAL    NUMBER,
  CON_VAL        NUMBER,
  MEOH_PCT       NUMBER,
  MEOH_VAL       NUMBER,
  MEOAC_PCT      NUMBER,
  MEOAC_VAL      NUMBER,
  HOAC_PCT       NUMBER,
  HOAC_VAL       NUMBER,
  VAC_PCT        NUMBER,
  VAC_VAL        NUMBER,
  PVAC_PCT       NUMBER,
  PVAC_VAL       NUMBER,
  PERI_BEG_TIME  DATE,
  PERI_END_TIME  DATE,
  DENSTY         NUMBER,
  COEFFICIENT    NUMBER,
  MEOH_ADJ_VAL   NUMBER,
  MEOAC_ADJ_VAL  NUMBER,
  HOAC_ADJ_VAL   NUMBER,
  VAC_ADJ_VAL    NUMBER,
  PVAC_ADJ_VAL   NUMBER,
  REC_TYPE_ID    INTEGER
)

CREATE TABLE SMES.CU_STK_MEAS_MOD_CW_T
(
  MODL_REC_ID    INTEGER                        NOT NULL,
  MTRL_DES       VARCHAR2(2000 BYTE),
  STK_DES        VARCHAR2(2000 BYTE),
  MEAS_UNIT_DES  VARCHAR2(2000 BYTE),
  TAG_ID         VARCHAR2(2000 BYTE),
  UNIT_ID        INTEGER,
  STK_ID1        INTEGER,
  MTRL_ID1       INTEGER,
  STK_ID2        INTEGER,
  MTRL_ID2       INTEGER,
  STK_ID3        INTEGER,
  MTRL_ID3       INTEGER,
  REC_TYPE_ID    INTEGER,
  DISPLAY_ORDER  INTEGER
)

CREATE TABLE SMES.CU_STK_MTRL_INGR
(
  MTRL_REC_ID        NUMBER                     NOT NULL,
  STKHS_MEAS_REC_ID  NUMBER,
  MTRL_ID            NUMBER                     NOT NULL,
  MTRL_PRCNT         NUMBER                     NOT NULL,
  QUTY_RANK_ID       NUMBER                     DEFAULT -1
)

CREATE TABLE SMES.CU_UNIT_STATE_T
(
  UNIT_STATE_ID    NUMBER                       NOT NULL,
  UNIT_STATE_NAME  VARCHAR2(200 BYTE)
)

CREATE TABLE SMES.DIF_CONSTRAINTS
(
  TABLE_NAME       VARCHAR2(30 BYTE),
  VERSION_NUM      VARCHAR2(20 BYTE),
  CONSTRAINT_NAME  VARCHAR2(30 BYTE),
  CONSTRAINT_TYPE  VARCHAR2(1 BYTE)
)